# Generated by Django 5.1.4 on 2024-12-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
